using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MarkovBoi
{
    static class StringResources
    {

        public static string[] MYNAMS =
        {
            "markoviboi",
            "marvokiboi",
            "markobivoi",
            "markoviboy",
            "markovivoi",
            "markybarky",
            "MarkyBoi",
            "MarkyBoy",
            "MarkoBoi",
            "MarkoBoy",
            "MackoBoy",
            "Macromode",
            "maramara",
            "barabara",
            "BoiBoi",
            "MickyDicky",
            "MobyDick",
            "BashiBot",
            "InvestmentBanking",
            "JazzHands",
            "FlatMan",
            "Fitzgerald",
            "StunnedMuffin",
            "StancedCars",
            "Fantastico",
            "JumbleButt",
            "ElectronicArts",
            "FREEDLC",
            "JUSTICELEAGUE",
            "Redpill",
            "BluePill",
            "M'Lady",
            "Mlady",
            "Sandman",
            "Hasbeens",
            "StencilFace",
            "WhackDonk",
            "BestBotEver",
            "BestBot4lyf",
            "The Best Bot In The World",
            "The Best Bot Ever Created",





            //SUPER ALTS

            "Abholos",
            "Ammutseba",
            "Amon-Gorloth",
            "Aphoom-Zhah",
            "Arwassa",
            "Atlach-Nacha",
            "Ayi'ig",
            "Aylith",
            "Baoht Z'uqqa-Mogg",
            "Basatan",
            "B'gnu-Thun",
            "Bokrug",
            "Bugg-Shash",
            "Byatis",
            "Chaugnar Faugn",
            "Coatlicue",
            "Coinchenn",
            "Crom Cruach",
            "Cthaat",
            "Cthaeghya",
            "Cthugha",
            "Cthulhu",
            "Cthylla",
            "Ctoggha",
            "Cyäegha",
            "Cynothoglys",
            "Dhumin",
            "The Dweller in the Gulf",
            "Dygra",
            "Dythalla",
            "Dzéwà",
            "Eihort",
            "Ei'lor",
            "Etepsed Egnis",
            "Ghadamon",
            "Ghatanothoa",
            "Ghisguth",
            "Gi-Hoveg",
            "Glaaki",
            "Gleeth",
            "Gloon",
            "Gobogeg",
            "God of the Red Flux",
            "Gog-Hoor",
            "Gol-goroth",
            "Golothess",
            "The Green God",
            "Groth-Golka",
            "Gtuhanai",
            "Gurathnaka",
            "Gur'la-ya",
            "Gwarloth",
            "Gzxtyos",
            "Hastalÿk",
            "Hastur",
            "H'chtelegoth",
            "Haiogh-Yai",
            "Hnarqu",
            "Hziulquoigmnzhah",
            "Idh-yaa",
            "Inpesca",
            "Istasha",
            "Ithaqua",
            "Janai'ngo",
            "Juk-Shabb",
            "Kaalut",
            "Kag'Naru of the Air",
            "Kassogtha",
            "Kaunuzoth",
            "Khal'kru",
            "Klosmiebhyx",
            "K'nar'st",
            "Krang",
            "Kthaw'keth",
            "Kurpannga",
            "Lexur'iga-serr'roth",
            "Lythalia",
            "Mappo no Ryujin",
            "M'basui Gwandu",
            "M'Nagalah",
            "Mnomquah",
            "Mordiggian",
            "Mormo",
            "Mortllgh",
            "Mynoghra",
            "Nctosa & Nctolhu",
            "Ngirrth'lu",
            "Northot",
            "Nssu-Ghahnb",
            "Nug and Yeb",
            "Nyaghoggua",
            "Nycrama",
            "Nyogtha",
            "Ob'mbu",
            "Oorn",
            "Othuum",
            "Othuyeg",
            "Perse",
            "Pharol",
            "Poseidon",
            "Psuchawrl",
            "Ptar-Axtlan",
            "Quachil Uttaus",
            "Quyagen",
            "Q'yth-az",
            "Raandaii-B'nk",
            "Ragnalla",
            "Raphanasuan",
            "Rhagorthua",
            "Rhan-Tegoth",
            "Rhogog",
            "Rh'Thulla of the Wind",
            "Rlim Shaikorth",
            "Rokon",
            "Saaitii",
            "Scathach",
            "Sebek",
            "Sedmelluq",
            "Sfatlicllp",
            "Shaklatal",
            "Shathak",
            "Shaurash-Ho",
            "Sheb-Teth",
            "Shista",
            "Shlithneth",
            "Sho-Gath",
            "Shterot",
            "Shudde M'ell",
            "Shuy-Nihl",
            "Sthanee",
            "S'tya-Yg'Nalle",
            "Summanus",
            "Swarog",
            "Thanaroa",
            "Tharapithia",
            "Thasaidon",
            "Th'rygh",
            "Tsathoggua",
            "Tulushuggua",
            "Turua",
            "Uitzilcapac",
            "Ut'Ulls-Hr'Her",
            "Vhuzompha",
            "Vibur",
            "Vile-Oct",
            "Volgna-Gath",
            "Voltiyig",
            "Vthyarilops",
            "Vulthoom",
            "The Worm that Gnaws in the Night",
            "Xalafu",
            "Xcthol",
            "Xinlurgash",
            "Xirdneth",
            "Xitalu",
            "Xotli",
            "Xoxiigghua",
            "Yegg-Ha",
            "Y'golonac",
            "Yhagni",
            "Yhashtur",
            "Yig",
            "'Ymnar",
            "Yog-Sapha",
            "Yorith",
            "Ysbaddaden",
            "Ythogtha",
            "Yug-Siturath",
            "Zathog",
            "Zhar and Lloigor",
            "Zindarak",
            "Zoth-Ommog",
            "Zstylzhemghi",
            "Zushakon",
            "Z'toggua",
            "Zvilpogghua",




            "The Dreaded One"

        };

        public static string[] MYNAMS2 =
        {

            "bitch please",
            "double trouble",
            "meme time",
            "pushup",
            "durr",
            "hurr",
            "memes",
            "tell me a story",
            "show me the money",
            "sucks to be you",
            "horse shit",
            "slutty",
            "fantastic",
            "does that shit",
            "when you know",
            "wasted",
            "in the dick",
            "fun times",
            "well how do you do",
            "i don't even",
            "i dont even",
            "this isn't even",
            "this isnt even",
            "he dead",
            "he dies",
            "she dies",
            "understandable",
            "asshat",
            "flippy dippy",
            "stunlock",
            "gridbounce",
            "happy chappy",
            "crunch time",
            "deepthott",
            "ass hats",
            "whores",
            "this bot",
            "my friend",
            "your friend",
            "i'm afraid",
            "im afraid",
            "noods",
        };

        public static string[] nonowords =
        {
            "nigger",
            "chinaman",
            "cunt",
            "faggot",
            "supertestbadword",
            "gamer girl sweat"
        };

        public static string[] lovecraftquotes =
        {
            "That is not dead which can eternal lie, And with strange aeons even death may die.",
            "The oldest and strongest emotion of mankind is fear, and the oldest and strongest kind of fear is fear of the unknown.",
            "The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents.",
            "The world is indeed comic, but the joke is on mankind.",
            "Searchers after horror haunt strange, far places.",
            "Ocean is more ancient than the mountains, and freighted with the memories and the dreams of Time.",
            "Almost nobody dances sober, unless they happen to be insane.",
            "Blue, green, grey, white, or black; smooth, ruffled, or mountainous; that ocean is not silent.",
            "From even the greatest of horrors irony is seldom absent.",
            "I never ask a man what his business is, for it never interests me. What I ask him about are his thoughts and dreams.",
            "Pleasure to me is wonder—the unexplored, the unexpected, the thing that is hidden and the changeless thing that lurks behind superficial mutability.",
            "Almost nobody dances sober, unless they happen to be insane.",
            "From even the greatest of horrors irony is seldom absent.",
            "That is not dead which can eternal lie, And with strange aeons even death may die.",
            "The most merciful thing in the world, I think, is the inability of the human mind to correlate all its contents... some day the piecing together of dissociated knowledge will open up such terrifying vistas of reality, and of our frightful position therein, that we shall either go mad from the revelation or flee from the light into the peace and safety of a new Dark Age.",
            "To be bitter is to attribute intent and personality to the formless, infinite, unchanging and unchangeable void. We drift on a chartless, resistless sea. Let us sing when we can, and forget the rest..",
            "I know always that I am an outsider; a stranger in this century and among those who are still men.",
            "It is good to be a cynic — it is better to be a contented cat — and it is best not to exist at all.",
            "At night, when the objective world has slunk back into its cavern and left dreamers to their own, there come inspirations and capabilities impossible at any less magical and quiet hour. No one knows whether or not he is a writer unless he has tried writing at night.",
            "I have seen the dark universe yawning, Where the black planets roll without aim, Where they roll in their horror unheeded,Without knowledge, or lustre, or name.",
            "If I am mad, it is mercy! May the gods pity the man who in his callousness can remain sane to the hideous end!",
            "I never ask a man what his business is, for it never interests me. What I ask him about are his thoughts and dreams.",
            "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn.",
            "Pleasure to me is wonder—the unexplored, the unexpected, the thing that is hidden and the changeless thing that lurks behind superficial mutability. To trace the remote in the immediate; the eternal in the ephemeral; the past in the present; the infinite in the finite; these are to me the springs of delight and beauty.",
            "We live on a placid island of ignorance in the midst of black seas of infinity, and it was not meant that we should voyage far.",
            "The oldest and strongest emotion of mankind is fear.",
            "Ultimate horror often paralyses memory in a merciful way.",
            "In his house at R'lyeh, dead Cthulu waits dreaming",
            "turn around."
        };

        public static string[] BenderQuotes =
        {
            "Uh, can people who hate Star Trek leave?",
            "Because he's a loser, that's why. He's the lobster equivalent of Fry.",
            "Ah, yes! John Quincy Adding Machine. He struck a chord with the voters when he pledged not to go on a killing spree.",
            "I'm 40% zinc!",
            "And I'd do it again! And perhaps a third time! But that would be it.",
            "There was nothing wrong with that food. The salt level was 10% less than a lethal dose.",
            "Oh, and I suppose Pitch-o-Mat 5000 was just a modified howitzer!",
            "Kill all humans, kill all humans, must kill all humans...",
            "Hey there sexy mama. Wanna kill all humans?",
            "I'm going to build my own theme park! With blackjack! And hookers!",
            "After all, our love isn't any different from yours. Except it's hotter, 'cause I'm involved.",
            "This is the worst kind of discrimination: the kind against me!",
            "Of all the friends I've had... you're the first.",
            "Have you ever tried just turning off the TV, sitting down with your children, and hitting them?",
            "I can hit you over the head until you think that's what happened.",
            "My life, and by extension everyone else's, is meaningless.",
            "I came here with a simple dream...a dream of killing all humans. And this is how it must end?",
            "Blackmail's such an ugly word. I prefer extortion. The X makes it sound cool.",
            "Bite my shiny metal ass!",
            "Everybody's a jerk: you, me, this jerk.",
            "I hate the people that love me, and they hate me.",
            "A grim day for robot-kind. But we can always build more killbots.",
            "I'm gonna drink 'til I reboot.",
            "What kind of party is this? There's no booze and only one hooker.",
            "I assure you, I barely know the meaning of the word labor.",
            "I'm a fraud. A poor, lazy, sexy fraud.",
            "And I'd do it again, and perhaps a third time. But that would be it.",
            "The auxiliary power's out and they spilled my cocktail.",
            "This'll teach those filthy bastards who's lovable!",
            "Why can't she just drink herself happy like a normal person?",
            "They're not very heavy, but you don't hear me not complaining.",
            "I'm finally richer than those snooty ATM machines.",
            "Compare your lives to mine and kill yourselves.",
            "Bodies are for hookers and fat people.",
            "Comedy's a dead art form. Now tragedy, that's funny.",
            "Ah, nothing like a warm fire and a SuperSoaker of fine cognac.",
            "He's no different from the rest of you organisms, shooting DNA at each other to make babies. I find it offensive.",
            "Now, my usual fee is $500. But seeing as how its you, I'll need it all in advance.",
            "She is well-traveled, and I don't mean she travels a lot.",
            "It's one thing to win a fixed fight; there's dignity in that. But to lose!",
            "Arrr! The laws of science be a harsh mistress.",
            "This is the best nanosecond of my life! No this one is! No this one!",
            "Problem solved. You two fight to the death and I'll cook the loser.",
            "Great is OK, but amazing would be GREAT!",
            "Yes! I'm going to be rich! You are too, but it's hard to get excited about that.",
            "Hmm, words I never say... Oh, I know: \"Thanks\"!",
            "Robot porno theatre! I was in that... general... vicinity.",
            "I can't afford to keep running people over. I'm not famous enough to get away with it.",
            "That probulator really knows how to please a man.",
            "Life is hilariously cruel.",
            "If you want children beaten, you've got to do it yourself.",
            "Robots don't have any emotions and sometimes that makes me very sad.",
            "You bastard! They treated me like an animal and that's what I became! ...Nah I'm just kidding, good to see ya buddy!",
            "Oh my god. I'm so excited I wish I could wet my pants!",
            "Shut up baby, i know it!"
        };

        public static string[] colorList =
           {
                "!blue",
                "!gold",
                "!green",
                "!orange",
                "!pink",
                "!purple",
                "!red",
                "!white",
                "!yellow",
                "!aqua",
                "!fuchsia",
                "!maroon",
                "DOOF DOOF DOOF DOOF",
                "THIS TRACK IS SICK"

            };

        public static string[] enders = { ". ", ", ", "! " };

    }
}
